### ISSUE TITLE
Change informational text notification on Providers page

### ISSUE THREAD

**Issue by vconzola** [konveyor/virt-ui#37]
The notification that appears the first time a user sees the Providers table telling them the benefits of uploading to cloud.redhat.com should have this text, "You can analyze your VMware provider data with the Red Hat Migration Analytics service. Migration Analytics generates a complete inventory of your VMware environment and VM recommendations for migration. Select your VMware providers and download the data file. Then log in to cloud.redhat.com, select Migration Analytics, and create a Migration Analytics report."

**Comment by apinnick** [comment]
Updated text: 

"You can analyze your VMware provider data with Migration Analytics. Migration Analytics generates a complete inventory of your VMware environment and VM recommendations for migration. Select your VMware providers and download the data file. Then log in to cloud.redhat.com, select Migration Analytics, and create a Migration Analytics report."

Removing "Red Hat" in order to comply with branding and style conventions.
