### ISSUE TITLE
PF Select ignores aria-label propagation from SimpleSelect, generating `serious` error.

### ISSUE THREAD

**Issue by gildub** [konveyor/virt-ui#88]
It seems like Select triggered from SimpleSelect is simply ignoring aria-label which is propagated via ...props.
I tried to force by adding aria-label explicitly to `Select` component with the same result

```
serious: ARIA input fields must have an accessible name https://dequeuniversity.com/rules/axe/3.5/aria-input-field-name?application=axeAPI index.js:216
Element:  
<ul id="target-provider" class="pf-c-select__menu" role="listbox">
index.js:114
HTML: <ul class="pf-c-select__menu" role="listbox" id="target-provider"> index.js:122
Fix any of the following:
  aria-label attribute does not exist or is empty
  aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
  Element has no title attribute or the title attribute is empty react_devtools_backend.js:2273:24
```
​
To reproduce:
Use any component calling `SimpleSelect` and make sure aria-label prop is define in the SimpleSelect call. 
For example use `AddEditMappingModal` and then in debug mode (dev tools) click on any select field, the error should appear in console.

**Comment by mturley** [comment]
The `aria-label` shouldn't be necessary because the `FieldGroup` has a `label` prop and a `fieldId` prop, which renders to HTML `<label for="fieldId">` which should alleviate the need for an aria-label, at least I thought. Maybe that doesn'tw ork right with `role="listbox"`. Definitely something to look into.

There are a bunch of other accessibility warnings we're getting from react-axe as well, we have an issue to loop back and address them: https://github.com/konveyor/virt-ui/issues/69

**Comment by gildub** [comment]
Oh ok, I missed that one. No worries closing this one then.

**Comment by mturley** [comment]
We can leave it open if you like! It includes specific details.

**Comment by mturley** [comment]
@gildub I ran into this all over the plan wizard as well, and after inspecting the `<label for="....">` behavior I guess that isn't accepted by that react-axe rule for some reason. I agree it's an issue upstream in PF. Opened a PR to fix it: https://github.com/patternfly/patternfly-react/pull/4931

**Comment by mturley** [comment]
The upstream PR was merged and released, and I'm fixing this in kubev2v/forklift-ui#100
